In [ ]:
import numpy as np
import pandas as pd

## PRACTICE ASSIGNMENT

In [ ]:
# (Common data for 1,2,3)
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.', 
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']

Q1. Vectorize the given text data using countvectorizer() object. What is the shape of text_data after vectorization?

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer().fit(text_data)
vector = vectorizer.transform(text_data)
vector.shape

(9, 99)

Q2. What is the shape of text_data after vectorization after the term that appeared in less than 2 documents are ignored?

In [ ]:
df = pd.DataFrame(vector.toarray())
pd.value_counts(df.sum(axis = 0) > 1)

False    79
True     20
dtype: int64

Q3. What is the token associated with word "metaverse"?

In [ ]:
vectorizer.vocabulary_['metaverse']

51

Q4. Write a code to convert the below text into an array after tokenizing it using countvectorizer with 10 features. What will be the output?

In [ ]:
Docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]

In [ ]:
vectorizer_docs = CountVectorizer(max_features=10).fit_transform(Docs)
vectorizer_docs.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1]])

Q5. Define a function called k_closest in python with the following signature:

```def k_closest(X: "set of vectors as np.ndarray", p: "test vector as np.array", k: "integer. Default 1") -> np.ndarray```

Which returns closest vectors in X which are closest to the vector p. Use the appropriate sklearn methods.

Consider, ```X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]])``` ```p= np.asarray([[0,0,0]])``` and ```k=1```

For these values, what is the output of the function?

In [ ]:
from sklearn.metrics.pairwise import euclidean_distances

def k_closest(X, p, k = 1) -> np.ndarray :
  min_dist, index = np.inf, -1
  for i in range(X.shape[0]) :
    dist = euclidean_distances(X[i].reshape(1, -1), p)
    if dist < min_dist :
      min_dist, index = dist, i
  return X[index]


X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]])
p= np.asarray([[0,0,0]])
k_closest(X, p)

array([20, 47, 88])

Q6. Define a function called distance in python with the following signature: 

```def distance( x0 : "A vector as np.array", X: "A list of vectors as np.ndarray", p : "p value for Minkowsky distance. Default 2, for Eucledian"):```

which returns a list of calculated Minkowsky distances between the point x0 and all points in X. Recall that the p-Minkowsky distance between $x=(x_1,x_2,…x_n)^T$ and $y=(y_1,y_2,…y_n)^T$ is 
$δ(x,y)=(|x_1−y_1|^p+|x_2−y_2|^p+⋯+|x_n−y_n|^p)^{\frac{1}{p}}$

Do not use any predefined function to calculate the same. 

Consider, X0 = np.array([1,0,0,0]), X= np.asarray([[1, 0, 0,0], [0, 1, 1,1],[1,2,0,0]]), p= 2 then, what is the output of the function distance(X0,X,p) ?

In [ ]:
def distance( X0, X, p = 2):
  res = np.zeros(X.shape[0])
  for i in range(X.shape[0]) :
    ans = 0
    for j in range(X.shape[1]) :
      ans += (X[i,j] - X0[j])**p
    res[i] += ans**(1/p)
  return res

X0 = np.array([1,0,0,0])
X= np.asarray([[1, 0, 0,0], [0, 1, 1,1],[1,2,0,0]])
distance( X0, X)

array([0., 2., 2.])

(Common data for Q7 to 11 Practice)

 Load digit dataset on Colab (datasets.load_digits()) and use softmax regression to build the model Using following steps.
 
 Step 1: Load the dataset and split it using train_test_split by keeping: test_size= 0.2 random_state=10

 Step 2: Use standard scaler as a scaling function to scale the training as well as test data.

 Step 3: Use Logisticregression() as an estimator and set parameter (multi_class='multinomial', solver='sag') to predict the output.

In [ ]:
from sklearn.datasets import load_digits
data = load_digits(as_frame = True)
X = data.data
y = data.target

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

pipeline = Pipeline([('scaler', StandardScaler()),
                     ('regression', LogisticRegression(multi_class='multinomial', solver = 'sag'))])

pipeline.fit(X_train, y_train)
y_test_predicted = pipeline.predict(X_test)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,


Q7. What is the shape of features data you got in digits dataset ?

In [ ]:
X.shape

(1797, 64)

Q8. How many labels are there in the dataset?

In [ ]:
len(y.unique())

10

Q9. How many times label 7 is there in the dataset?

In [ ]:
pd.value_counts(y == 7)[True]

179

Q10. What is the accuracy of the trained model on test data?

In [ ]:
from sklearn.metrics import accuracy_score, f1_score

accuracy_score(y_test, y_test_predicted)

0.9694444444444444

Q11. Write the f1_score value you got .(Keep parameter average='weighted')

In [ ]:
f1_score(y_test, y_test_predicted, average='weighted')

0.9697233182569327

## GRADED ASSIGNMENT

**(Common data for Q1 to Q5 graded questions)**

Step 1: Download the dataset using following link: (https://drive.google.com/file/d/1v-uxWEgTI0GDCOTZOX3shUMkTf1a_CL7/view?usp=sharing)

Step 2: Import the data in google colab using pd.read_csv().

Step 3: Seperate features and target data in seperate variable X and Y.

Step 4: Convert dataframe X and series y into array and save it in variable X_array,y_array.

Step 5: Split the dataset using train_test_split. (Keep parameter train_size=0.7 and random_state=10).

Step 6: Reshape the dataset in such a way that each entry of data has 90 samples.

Step 7: Use SGD regressor as an estimator and partial_fit to fit the dataset on the model. (Set random_state=10)

Step 8: Calculate different evaluation metrics value like mean_square_error, R2_score.

Use the training set for fitting the model and use the test data to make the predictions.

Note: No need to scale the data. It's already scaled.

Answer the below questions.

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Assignment_files/MLP/data_for_large_scale.csv')
X, y = data[data.columns[:-1]], data['Target']
X_array, y_array = X.to_numpy(), y.to_numpy()
X_array_train, X_array_test, y_array_train, y_array_test = train_test_split(X_array, y_array, train_size = 0.7, random_state = 10)
# X_array_train, X_array_test = X_array_train.reshape(90, 10, -1), X_array_test.reshape(90, 10, -1)

In [ ]:
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error, r2_score
sgd = SGDRegressor(random_state = 10)
for i in range(X_array_train.shape[0]//90) :
  sgd.partial_fit(X_array_train[90*i:90*(i+1)], y_array_train[90*i:90*(i+1)])

Q1. How many fetaures are there in the dataset?

In [ ]:
X.shape[1]

10

Q2. What is the value of intercept you got after training the model using SGDRegressor?(select the closest answer)

In [ ]:
sgd.intercept_

array([-0.00841686])

Q3. What is the value of cofficient corresponding to "feature-3"you got after trainig the model using SGDRegressor? (select the closest answer)

In [ ]:
sgd.coef_[2]

81.24038266340611

Q4. What is the value of R2 score for test data?

In [ ]:
y_array_test_predict = sgd.predict(X_array_test)
r2_score(y_array_test, y_array_test_predict)

0.999991968905383

Q5. What is the value of cofficient corresponding to "feature-5" after 5th iteration?

In [ ]:
sgd = SGDRegressor(random_state = 10)
for i in range(5) :
  sgd.partial_fit(X_array_train[90*i:90*(i+1)], y_array_train[90*i:90*(i+1)])

In [ ]:
sgd.coef_[4]

57.85396643897833

**(Common data for Q6 to Q8 Graded questions)**

This dataset was constructed by adding elevation information to a 2D road network in North Jutland, Denmark (covering a region of 185 x 135 km^2). Elevation values where extracted from a publicly available massive Laser Scan Point Cloud for Denmark. This 3D road network was eventually used for benchmarking various fuel and CO2 estimation algorithms. This dataset can be used by any applications that require to know very accurate elevation information of a road network to perform more accurate routing for eco-routing, cyclist routes etc. For the data mining and machine learning community, this dataset can be used as 'ground-truth' validation in spatial mining techniques and satellite image processing. It has no class labels,

Use this dataset to guess some missing elevation information for some points on the road.

Column names:

OSM_ID: OpenStreetMap ID for each road segment or edge in the graph.

LONGITUDE: Web Mercaptor (Google format) longitude

LATITUDE: Web Mercaptor (Google format) latitude

ALTITUDE: Height in meters.

Load the dataset from link("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt"). Set parameter chunk size=20000 and iterator =True in pd.read_csv().

NOTE: The above file doesn't have column names

Scale your whole dataset first with standard scalar using partial_fit method. Then use SGDRegressor(random state=10) on the dataset and answer the following.

In [ ]:
from sklearn.preprocessing import StandardScaler
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", chunksize=20000, iterator=True, names=['OSM_ID','LONGITUDE','LATITUDE','ALTITUDE'])
scaler = StandardScaler()
sgd = SGDRegressor(random_state=10, max_iter=7)

for chunk in data :
  X, y = chunk[chunk.columns[:-1]], chunk['ALTITUDE']
  X_scaled = scaler.partial_fit(X)
  X_scaled = scaler.transform(X)

sgd.fit(X_scaled, y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1507: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,


SGDRegressor(max_iter=7, random_state=10)

Q6. Check how many total samples are there in the dataset?



In [ ]:
pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", header = None).shape[0]

434874

Q7. What is the value of intercept after 7th iteration. (select the closest option).

In [ ]:
sgd.intercept_

array([21.84911436])

Q8. What is the value of cofficient corresponding to longitude feature after 7th iteration.(select the closest option).

In [ ]:
sgd.coef_[1]

3.8296130236292396

**(Common data for Q9 to 11)**

Load Iris datset on Colab and use KNN classifier to build the model Using following steps.

Step 1: Load the dataset and split it using train_test_split by keeping: test_size= 0.2 random_state=10

Step 2: Use Normalizer() as a scaling function to scale the data.

Step 3: Use KNeighborsClassifier(K) as an estimator to predict the output.

In [ ]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score, f1_score

X, y = load_iris(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2, random_state = 10)
pipeline2 = Pipeline([('scaler', Normalizer()),
                     ('knn', KNeighborsClassifier(n_neighbors = 2))])
pipeline3 = Pipeline([('scaler', Normalizer()),
                     ('knn', KNeighborsClassifier(n_neighbors = 3))])
pipeline4 = Pipeline([('scaler', Normalizer()),
                     ('knn', KNeighborsClassifier(n_neighbors = 4))])
y_test_predict2 = pipeline2.fit(X_train, y_train).predict(X_test)
y_test_predict3 = pipeline3.fit(X_train, y_train).predict(X_test)
y_test_predict4 = pipeline4.fit(X_train, y_train).predict(X_test)

Q9. Which of the following K value gives the best accuracy on test set.

In [ ]:
accuracy_score(y_test, y_test_predict2), accuracy_score(y_test, y_test_predict3), accuracy_score(y_test, y_test_predict4)

(0.9666666666666667, 0.9666666666666667, 0.9666666666666667)

Q10. What is the accuracy for k=3?

In [ ]:
accuracy_score(y_test, y_test_predict3)

0.9666666666666667

Q11. Compute wieghted F1 score value for k=3.(Keep parameter average='weighted')

In [ ]:
f1_score(y_test, y_test_predict3, average='weighted')

0.9671111111111111